packages:
  - '!**/.*/**'
  - '!**/artifacts/**'
  - 'packages/*'
  - 'common-features'
  - 'common-features/src/*'
  - 'serene/src/Serene.Web'

catalogs:
  serenity:
    "@vitest/coverage-v8": "3.2.4"
    "chart.js": "4.5.1"
    "esbuild": "0.25.11"
    "glob": "11.0.3"
    "jsdom": "27.0.0"
    "typescript": "5.9.3"
    "vitest": "3.2.4"